[package]
name = "cdk_toolkit_prototype"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.117"
colored = "2.0"
dialoguer = "0.11.0"

[[bin]]
name = "cdk"
path = "src/cdk.rs"